-- Demo Sample: Generated Code Examples
-- Shows what Claude AI generates when following QUAD Agent Rules
--
-- Purpose: For demos - show REAL code output, not dummy data
-- Created: January 2026

-- This table stores sample generated code for demo purposes
CREATE TABLE IF NOT EXISTS quad_demo_code_samples (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    industry        VARCHAR(100) NOT NULL,
    activity_type   VARCHAR(100) NOT NULL,
    task_description TEXT NOT NULL,
    generated_code  TEXT NOT NULL,
    language        VARCHAR(50) NOT NULL,
    created_at      TIMESTAMP DEFAULT NOW()
);

-- Sample 1: Investment Banking - Add Payment API
INSERT INTO quad_demo_code_samples (industry, activity_type, task_description, language, generated_code) VALUES
('investment_banking', 'add_api_endpoint', 'Add payment processing API for wire transfers', 'java',
'package com.massmutual.payments.controller;

import com.massmutual.common.logging.MMLogger;
import com.massmutual.compliance.FinraAuditService;
import com.massmutual.reporting.SecReportingService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.Map;
import java.util.UUID;

/**
 * Wire Transfer Payment Controller
 *
 * Generated by QUAD Story Agent following rules:
 * ✅ DO: Use Java Spring Boot
 * ✅ DO: Add FINRA compliance logging
 * ✅ DO: Validate with BigDecimal (not float)
 * ✅ DO: Use MMLogger (MassMutual internal)
 * ✅ DO: Add SEC reporting hooks
 * ❌ DON''T: Store PII in logs
 * ❌ DON''T: Use reflection
 */
@RestController
@RequestMapping("/api/v1/payments/wire")
public class WireTransferController {

    // Using MMLogger per MassMutual org rules (not Log4j)
    private static final MMLogger log = MMLogger.getLogger(WireTransferController.class);

    private final PaymentService paymentService;
    private final FinraAuditService finraAudit;
    private final SecReportingService secReporting;

    public WireTransferController(
            PaymentService paymentService,
            FinraAuditService finraAudit,
            SecReportingService secReporting) {
        this.paymentService = paymentService;
        this.finraAudit = finraAudit;
        this.secReporting = secReporting;
    }

    @PostMapping("/initiate")
    public ResponseEntity<WireTransferResponse> initiateTransfer(
            @Valid @RequestBody WireTransferRequest request) {

        String transactionId = UUID.randomUUID().toString();

        // FINRA compliance logging (no PII - just transaction metadata)
        log.audit("Wire transfer initiated", Map.of(
            "transactionId", transactionId,
            "amount", request.getAmount().toPlainString(),
            "currency", request.getCurrency()
            // Note: NO account numbers, NO names logged (PII rule)
        ));

        // BigDecimal for financial precision (never float/double)
        BigDecimal amount = request.getAmount();
        BigDecimal fee = calculateFee(amount);
        BigDecimal total = amount.add(fee);

        // SEC reporting hook (MassMutual custom rule)
        secReporting.recordTransaction(
            transactionId,
            "WIRE_TRANSFER",
            total,
            request.getCurrency()
        );

        // Process the transfer
        WireTransferResult result = paymentService.processWireTransfer(
            transactionId,
            request.getSourceAccountId(),
            request.getDestinationRoutingNumber(),
            request.getDestinationAccountNumber(),
            total
        );

        // FINRA audit trail
        finraAudit.logTransaction(transactionId, "WIRE_INITIATED", result.getStatus());

        return ResponseEntity.ok(new WireTransferResponse(
            transactionId,
            result.getStatus(),
            total,
            result.getEstimatedCompletionTime()
        ));
    }

    private BigDecimal calculateFee(BigDecimal amount) {
        // 0.1% fee with minimum $25
        BigDecimal percentFee = amount.multiply(new BigDecimal("0.001"));
        BigDecimal minFee = new BigDecimal("25.00");
        return percentFee.max(minFee);
    }
}');

-- Verification
SELECT industry, activity_type, language, LENGTH(generated_code) as code_length
FROM quad_demo_code_samples;
